version: '2'
services:
  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    ports:
      - "8112:8112"
      - "56881-56889:56881-56889"
      - "56890-57200:56890-57200"
    network_mode: host
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa\Johannesburg
      - UMASK_SET=022
      - DELUGE_LOGLEVEL=error  
    volumes:
      - /deluge/config:/deluge/config
      - /deluge/downloads:/deluge/downloads